[package]
name = "typr"
version = "0.1.1"
edition = "2021"
authors = ["Fabrice Hategekimana <fab.hatege15@gmail.com>"]
description = "A superset of the legendary R"
license = "MIT"
repository = "https://github.com/fabriceHategekimana/typr"
keywords = ["R", "type-checker", "language", "transpiler"] 
readme = "README.md"

[dependencies]
nom = "7.1.3"
serde = {version = "1.0.215", features = ["derive"]}
serde_json = "1.0.133"

